### ISSUE TITLE
Add option to generate meaningful names for colors

### ISSUE THREAD

**Issue by AdrianSimionov** [verocloud/color-sorting-cli#23]
Given an input TXT file, generate a meaningful name for each color and populate the TXT file.

If there is no color following a space after the HEX or RGB color, add the name of the color.
If some lines have a color name, add an option to either re-write the color with the newly generated one, or preserve the old color name and generate a color name only for the lines which do not have a name.

Please take a look at the following project, written in JS, which should give you an understanding of how such a task can be achieved. Please note some of these projects are licensed under various terms.

https://www.color-blindness.com/color-name-hue/

**Comment by xlurio** [comment]
Solved on 5f80f84fa0c86ccf0b5b00e9eec03adaef5adb7f
