### ISSUE TITLE
image2txt: allow generating a palette with a fixed number of colors

### ISSUE THREAD

**Issue by AdrianSimionov** [verocloud/color-sorting-cli#45]
Given a PNG file which after noise removal generates a palette with N colors, allow the user to ask via an optional parameter the generation of a palette which has a fixed M number of colors, the most popular colors found, in reverse order (most found color, having the highest priority).

Assumes M <= N.

If M > N, generate a palette with N colors, and notify the user than only N colors were found although M colors were asked.

**Comment by xlurio** [comment]
solved with #105
