### ISSUE TITLE
txt2image: write HEX code, RGB and name on color

### ISSUE THREAD

**Issue by AdrianSimionov** [verocloud/color-sorting-cli#46]
When generating a palette PNG file, on top of the color, centered both vertically and horizontally, on 3 different lines, add the following text:

Line 1: Hex value starting with #
Line 2: RGB value, withing parenthesis.
Line 3: Color name.

Choose the text color to avoid low contract with background. Check WCAG 2.1 rule 1.4.3.
https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html

**Comment by xlurio** [comment]
Solved on https://github.com/verocloud/color-sorting-cli/pull/103
