### ISSUE TITLE
feat: hard-coded color palettes in JSON

### ISSUE THREAD

**Issue by AdrianSimionov** [verocloud/color-sorting-cli#81]
Add an option to build into the software custom pre-made color palettes.

The way it would work is that the tool would list all the hard-coded built-in palettes, and similar operations will be allowed as if the input would be an input file.

Operations should work in a similar fashion: output to various formats, rename the pre-coded names, generate PNG file to show colors and codes, export to various palette formats, etc.

While I am open for proposals, my initial view is:
- there will be a master JSON file which is indexing all prebuilt custom palettes and points to external JSON files which capture the colors and names
- each color palette is stored in it's own JSON file, in the form of HEX value and name, where name is optional, only HEX value is mandatory

Using JSON will allow others to easily make contributions with famous color palettes to be added, without too much extensive Python knowledge required.

**Comment by xlurio** [comment]
And in this initial view the JSON files with the custom palettes would be uploaded to the repository or be available for access in the internet?

**Comment by AdrianSimionov** [comment]
1. I would like it to be part of the source code, if possible, hard-coded.
2. A pull request is my expectation, but with very limited technical knowledge required, only around JSON files.

**Comment by xlurio** [comment]
Solved by #119
